"""
core/copilot/sandbox.py
=======================
Secure code execution sandbox for Voice Data Copilot.

Provides execute_pandas_code(), which runs LLM-generated Python/Pandas code
through AST static checks, restricted namespace execution, and stdout capture.
"""

import ast
import io
import math
import contextlib
import pandas as pd
import numpy as np
from core.copilot.imputer import advanced_impute
from core.copilot.cleaner import fast_clean, deep_clean

# Only these top-level module names may appear in import statements
ALLOWED_IMPORTS: frozenset = frozenset({
    "pandas", "numpy", "math", "statistics",
    "re", "json", "datetime", "collections",
    "sklearn", "scipy",
})

# These names are always forbidden — whether imported or used as attributes
BLOCKED_NAMES: frozenset = frozenset({
    "os", "sys", "subprocess", "shutil", "pathlib",
    "open", "eval", "exec", "compile", "globals", "locals",
    "__import__", "importlib", "socket", "urllib",
    "requests", "http", "ftplib", "smtplib",
    "builtins", "__builtins__",
})

# These cleaning/imputation names are forbidden to force using the native studio tools instead
FORBIDDEN_CLEANING_NAMES: frozenset = frozenset({
    "fillna", "dropna", "interpolate", "bfill", "ffill", "KNNImputer", "IterativeImputer"
})

# Safe builtins exposed to the sandbox namespace
_SAFE_BUILTINS: dict = {
    name: __builtins__[name]   # type: ignore[index]
    for name in (
        "abs", "all", "any", "bin", "bool", "chr", "dict", "dir",
        "divmod", "enumerate", "filter", "float", "format", "frozenset",
        "getattr", "hasattr", "hash", "hex", "int", "isinstance",
        "issubclass", "iter", "len", "list", "map", "max", "min",
        "next", "oct", "ord", "pow", "print", "range", "repr",
        "reversed", "round", "set", "slice", "sorted", "str", "sum",
        "tuple", "type", "vars", "zip", "True", "False", "None",
        "__import__",
    )
    if name in __builtins__  # type: ignore[operator]
}


class SecurityError(Exception):
    """Raised when the sandbox detects a security violation in the code."""


class _SecurityVisitor(ast.NodeVisitor):
    """Walk the AST of the submitted code and raise SecurityError on forbidden operations."""

    def visit_Import(self, node: ast.Import) -> None:
        for alias in node.names:
            top_level = alias.name.split(".")[0]
            if top_level not in ALLOWED_IMPORTS:
                raise SecurityError(
                    f"Import of '{alias.name}' is not permitted in the sandbox."
                )
        self.generic_visit(node)

    def visit_ImportFrom(self, node: ast.ImportFrom) -> None:
        module = (node.module or "").split(".")[0]
        if module not in ALLOWED_IMPORTS:
            raise SecurityError(
                f"Import from '{node.module}' is not permitted in the sandbox."
            )
        self.generic_visit(node)

    def visit_Name(self, node: ast.Name) -> None:
        if node.id in BLOCKED_NAMES:
            raise SecurityError(
                f"Use of '{node.id}' is not permitted in the sandbox."
            )
        if node.id in FORBIDDEN_CLEANING_NAMES:
            raise SecurityError(
                "SecurityError: Raw pandas cleaning methods are restricted. "
                "You MUST use the dedicated native tools (e.g., smart_impute_column_tool) "
                "for data cleaning and imputation."
            )
        self.generic_visit(node)

    def visit_Attribute(self, node: ast.Attribute) -> None:
        if node.attr in BLOCKED_NAMES:
            raise SecurityError(
                f"Access to attribute '{node.attr}' is not permitted in the sandbox."
            )
        if node.attr in FORBIDDEN_CLEANING_NAMES:
            raise SecurityError(
                "SecurityError: Raw pandas cleaning methods are restricted. "
                "You MUST use the dedicated native tools (e.g., smart_impute_column_tool) "
                "for data cleaning and imputation."
            )
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:
        if isinstance(node.func, ast.Name) and node.func.id in BLOCKED_NAMES:
            raise SecurityError(
                f"Call to '{node.func.id}' is not permitted in the sandbox."
            )
        self.generic_visit(node)


def _check_ast(code: str) -> None:
    """Parse and statically analyse the code string."""
    try:
        tree = ast.parse(code, mode="exec")
    except SyntaxError as e:
        raise SyntaxError(f"Syntax error in generated code: {e}") from e

    _SecurityVisitor().visit(tree)


def execute_pandas_code(code: str, df: pd.DataFrame) -> dict:
    """
    Safely execute a Pandas code snippet generated by the LLM.

    The code receives:
        df     — the user's active DataFrame
        pd     — pandas
        np     — numpy
        result — pre-seeded to None; the LLM should set this to its answer
    """
    if not code or not code.strip():
        return {"status": "runtime_error", "error": "Empty code string received.", "updated_df": None}

    # Layer 1: AST check
    try:
        _check_ast(code)
    except SecurityError as e:
        return {"status": "security_error", "error": str(e), "updated_df": None}
    except SyntaxError as e:
        return {"status": "syntax_error",   "error": str(e), "updated_df": None}

    # Setup audit log accumulation wrappers for sandbox functions
    existing_logs = df.attrs.get("audit_log", []) if hasattr(df, "attrs") and df.attrs else []
    execution_audit_logs = list(existing_logs) if isinstance(existing_logs, list) else []

    def wrap_fast_clean(data):
        nonlocal execution_audit_logs
        df_res, audit = fast_clean(data)
        if audit:
            execution_audit_logs.extend(audit)
        df_res.attrs["audit_log"] = execution_audit_logs
        return df_res

    def wrap_deep_clean(data, scaling=False):
        nonlocal execution_audit_logs
        df_res, audit = deep_clean(data, scaling=scaling)
        if audit:
            execution_audit_logs.extend(audit)
        df_res.attrs["audit_log"] = execution_audit_logs
        return df_res

    def wrap_clean_column_outliers(data, col):
        nonlocal execution_audit_logs
        from core.copilot.tools import clean_column_outliers
        df_res = clean_column_outliers(data, col)
        tool_logs = df_res.attrs.get("audit_log", [])
        for log in tool_logs:
            if log not in execution_audit_logs:
                execution_audit_logs.append(log)
        df_res.attrs["audit_log"] = execution_audit_logs
        return df_res

    def wrap_smart_impute_column(data, col):
        nonlocal execution_audit_logs
        from core.copilot.tools import smart_impute_column
        df_res = smart_impute_column(data, col)
        tool_logs = df_res.attrs.get("audit_log", [])
        for log in tool_logs:
            if log not in execution_audit_logs:
                execution_audit_logs.append(log)
        df_res.attrs["audit_log"] = execution_audit_logs
        return df_res

    def wrap_standardize_column_date(data, col):
        nonlocal execution_audit_logs
        from core.copilot.tools import standardize_column_date
        df_res = standardize_column_date(data, col)
        tool_logs = df_res.attrs.get("audit_log", [])
        for log in tool_logs:
            if log not in execution_audit_logs:
                execution_audit_logs.append(log)
        df_res.attrs["audit_log"] = execution_audit_logs
        return df_res

    def wrap_fuzzy_fix_column(data, col):
        nonlocal execution_audit_logs
        from core.copilot.tools import fuzzy_fix_column
        df_res = fuzzy_fix_column(data, col)
        tool_logs = df_res.attrs.get("audit_log", [])
        for log in tool_logs:
            if log not in execution_audit_logs:
                execution_audit_logs.append(log)
        df_res.attrs["audit_log"] = execution_audit_logs
        return df_res

    # Layer 2: Restricted namespace
    sandbox_globals: dict = {
        "__builtins__": _SAFE_BUILTINS,
        "pd":     pd,
        "np":     np,
        "math":   math,
        "df":     df.copy(),   # copy to prevent accidental in-place mutation
        "result": None,
        "advanced_impute": advanced_impute,
        "fast_clean": wrap_fast_clean,
        "deep_clean": wrap_deep_clean,
        "clean_column_outliers": wrap_clean_column_outliers,
        "smart_impute_column": wrap_smart_impute_column,
        "standardize_column_date": wrap_standardize_column_date,
        "fuzzy_fix_column": wrap_fuzzy_fix_column,
    }

    # Layers 3 & 4: stdout capture + exception isolation
    stdout_buffer = io.StringIO()
    try:
        with contextlib.redirect_stdout(stdout_buffer):
            exec(code, sandbox_globals)  # noqa: S102

        result  = sandbox_globals.get("result")
        stdout  = stdout_buffer.getvalue()

        # Normalise result to a readable string
        if result is None and stdout:
            result_str = stdout.strip()
        elif result is None:
            result_str = "Code executed successfully but `result` was not set."
        elif isinstance(result, pd.DataFrame):
            result_str = result.to_string(max_rows=20)
        elif isinstance(result, pd.Series):
            result_str = result.to_string(max_entries=30)
        else:
            result_str = str(result)

        updated_df: pd.DataFrame | None = sandbox_globals.get("df")
        if updated_df is not None:
            # Preserve the audit logs inside the dataframe attributes
            updated_df.attrs["audit_log"] = execution_audit_logs

        return {
            "status":     "ok",
            "result":     result_str,
            "stdout":     stdout.strip(),
            "updated_df": updated_df,
            "audit_log":  execution_audit_logs,
        }

    except Exception as e:
        return {
            "status":     "runtime_error",
            "error":      f"{type(e).__name__}: {e}",
            "updated_df": None,
        }
